package Interfaz;

import BD.GestionBD;
import Modelos.Productos;
import Modelos.Usuario;
import Modelos.Usuarios;
import Modelos.Venta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel López y Javier Fernández
 */
public class VentanaLogin extends javax.swing.JFrame {

    GestionBD conexion;
    ArrayList<JButton> listaBotonesUsuarios;
    
    public VentanaLogin() {
        
        // Creamos la conexión a la BD e inicializamos la lista de botones
        conexion = new GestionBD("localhost", "usuario",
                "usuario", "tpv"
        );
        listaBotonesUsuarios = new ArrayList();
        initComponents();
        annadirBotonesUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelNumeros = new javax.swing.JPanel();
        jButtonN7 = new javax.swing.JButton();
        jButtonN8 = new javax.swing.JButton();
        jButtonN9 = new javax.swing.JButton();
        jButtonN4 = new javax.swing.JButton();
        jButtonN5 = new javax.swing.JButton();
        jButtonN6 = new javax.swing.JButton();
        jButtonN1 = new javax.swing.JButton();
        jButtonN2 = new javax.swing.JButton();
        jButtonN3 = new javax.swing.JButton();
        jButtonN0 = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jPanelUsuarios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPV Login");

        jPanelNumeros.setLayout(new java.awt.GridBagLayout());

        jButtonN7.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN7.setText("7");
        jButtonN7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN7.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN7.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN7.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN7, gridBagConstraints);

        jButtonN8.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN8.setText("8");
        jButtonN8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN8.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN8.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN8.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN8, gridBagConstraints);

        jButtonN9.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN9.setText("9");
        jButtonN9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN9.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN9.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN9.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN9, gridBagConstraints);

        jButtonN4.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN4.setText("4");
        jButtonN4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN4.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN4.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN4.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN4, gridBagConstraints);

        jButtonN5.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN5.setText("5");
        jButtonN5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN5.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN5.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN5.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN5, gridBagConstraints);

        jButtonN6.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN6.setText("6");
        jButtonN6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN6.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN6.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN6.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN6, gridBagConstraints);

        jButtonN1.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN1.setText("1");
        jButtonN1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN1.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN1.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN1.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN1, gridBagConstraints);

        jButtonN2.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN2.setText("2");
        jButtonN2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN2.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN2.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN2.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN2, gridBagConstraints);

        jButtonN3.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN3.setText("3");
        jButtonN3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN3.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN3.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN3.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumeros.add(jButtonN3, gridBagConstraints);

        jButtonN0.setBackground(new java.awt.Color(14, 165, 231));
        jButtonN0.setText("0");
        jButtonN0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonN0.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonN0.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonN0.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanelNumeros.add(jButtonN0, gridBagConstraints);

        jButtonBorrar.setBackground(new java.awt.Color(234, 12, 12));
        jButtonBorrar.setText(" ⬅");
        jButtonBorrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonBorrar.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonBorrar.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonBorrar.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanelNumeros.add(jButtonBorrar, gridBagConstraints);

        jButtonValidar.setBackground(new java.awt.Color(17, 201, 33));
        jButtonValidar.setText("OK");
        jButtonValidar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonValidar.setMaximumSize(new java.awt.Dimension(75, 75));
        jButtonValidar.setMinimumSize(new java.awt.Dimension(75, 75));
        jButtonValidar.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanelNumeros.add(jButtonValidar, gridBagConstraints);

        jLabelLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelLogin.setText("Login:");

        jTextFieldLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextFieldLogin.setMinimumSize(new java.awt.Dimension(100, 40));
        jTextFieldLogin.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabelPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelPassword.setText("Código:");

        jTextFieldPassword.setEditable(false);
        jTextFieldPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextFieldPassword.setFocusable(false);
        jTextFieldPassword.setMinimumSize(new java.awt.Dimension(100, 40));
        jTextFieldPassword.setPreferredSize(new java.awt.Dimension(100, 40));

        jPanelUsuarios.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLogin)
                            .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassword)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN7ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "7");
    }//GEN-LAST:event_jButtonN7ActionPerformed

    private void jButtonN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN8ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "8");
    }//GEN-LAST:event_jButtonN8ActionPerformed

    private void jButtonN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN9ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "9");
    }//GEN-LAST:event_jButtonN9ActionPerformed

    private void jButtonN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN4ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "4");
    }//GEN-LAST:event_jButtonN4ActionPerformed

    private void jButtonN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN5ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "5");
    }//GEN-LAST:event_jButtonN5ActionPerformed

    private void jButtonN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN6ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "6");
    }//GEN-LAST:event_jButtonN6ActionPerformed

    private void jButtonN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN1ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "1");
    }//GEN-LAST:event_jButtonN1ActionPerformed

    private void jButtonN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN2ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "2");
    }//GEN-LAST:event_jButtonN2ActionPerformed

    private void jButtonN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN3ActionPerformed
        String valor = jTextFieldPassword.getText();
        jTextFieldPassword.setText(valor + "3");
    }//GEN-LAST:event_jButtonN3ActionPerformed

    private void jButtonN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN0ActionPerformed
        // Guardamos el contenido del textfield del password
        String valor = jTextFieldPassword.getText();

        // Actualizamos el valor
        jTextFieldPassword.setText(valor + "0");

        // Repetimos el mismo proceso con el resto de botones pero
        // con diferentes valores
    }//GEN-LAST:event_jButtonN0ActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // Guardamos el valor del password
        String valor = jTextFieldPassword.getText();
        // Si su longitud es diferente de 0, hacemos una subcadena quitando
        // el último carácter
        if (valor.length() != 0) {
            valor = valor.substring(0, valor.length() - 1);
            jTextFieldPassword.setText(valor);
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // Guardamos los valores del login y de la contraseña
        String login = jTextFieldLogin.getText();
        String password = jTextFieldPassword.getText();

        // Comprobamos si el usuario existe
        if (conexion.comprobarUsuario(login, Integer.parseInt(password))) {
            
            // Creamos el nuevo usuario y obtenemos los productos de la BBDD
            // para crear un objeto Venta
            Usuario user = conexion.obtenerUsuario(login, Integer.parseInt(password));
            Venta venta = new Venta(user);
            VentanaProductos ventanaProductos = new VentanaProductos(venta);
            JOptionPane.showMessageDialog( null,
                    "Te has logueado como " + login);
            this.setVisible(false);
            ventanaProductos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog( null,
            "Los datos introducidos no coinciden en la Base de Datos");
        }
        
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonN0;
    private javax.swing.JButton jButtonN1;
    private javax.swing.JButton jButtonN2;
    private javax.swing.JButton jButtonN3;
    private javax.swing.JButton jButtonN4;
    private javax.swing.JButton jButtonN5;
    private javax.swing.JButton jButtonN6;
    private javax.swing.JButton jButtonN7;
    private javax.swing.JButton jButtonN8;
    private javax.swing.JButton jButtonN9;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanelNumeros;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables

    public void annadirBotonesUsuarios(){
        Usuarios usuarios = conexion.listarUsuarios();
        
        // Añadir los botones
        for (int i = 0; i < usuarios.size(); i++) {
            JButton boton = new JButton(usuarios.obtenerUsuarioPorPosicion(i).getNombre() + 
                    " " + usuarios.obtenerUsuarioPorPosicion(i).getApellidos());
            boton.setName(usuarios.obtenerUsuarioPorPosicion(i).getLogin());
            listaBotonesUsuarios.add(boton);
        }
        
        // Darles funcionalidad
        for (JButton boton : listaBotonesUsuarios) {
            jPanelUsuarios.add(boton);
            boton.setSize(100, 100);
            boton.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Cuando pulsemos sobre el botón se añadirá el login
                    // al jTextField del login
                    jTextFieldLogin.setText(boton.getName());
                    jTextFieldPassword.setText("");
                }
            
            });
            boton.setVisible(true);
        }
    }
}